test-default:
  image: alpine:3.18
  stage: test
  script:
    - apk upgrade -U -a
    - apk add python3 py3-flask py3-pytest py3-pytest-cov py3-pip py3-requests py3-yaml py3-dotenv py3-requests-mock
    - pip install -r requirements.txt
    - python3 -m pytest -v --cov=secfixes_tracker --cov-report term-missing --cov-report xml tests/
  coverage: /^TOTAL.+?(\d+\%)$/
  artifacts:
    expire_in: 30 days
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
  tags:
    - docker-alpine
    - x86_64
